name: Ini-cpp pipelines
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types:
      - opened
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref}}
  cancel-in-progress: true

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v4
      - name: format check
        run: |
          files=$(git diff --name-only -r HEAD^1 HEAD | grep 'src\/' | grep -E '\.(cc|h)$' | sed "s/^/${workspace_path}\//" | tr '\n' ' ')
          if [ ! -z "$files" ]
          then
            python3 ${{github.workspace}}/tools/cpplint.py --verbose=3 --filter=-build/include_subdir,-build/include_what_you_use,-build/c++11  ${files}
          else
            echo "No source files changed!"
          fi
      - name: clang-tidy check
        working-directory: ${{github.workspace}}/
        run: |
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
          echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main" | sudo tee -a /etc/apt/sources.list
          echo "deb-src http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main" | sudo tee -a /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install clang-tidy-18
          if [ ! -f /usr/lib/llvm-18/bin/clang-tidy ]
          then
            echo "clang-tidy-18 not found!"
            exit 1
          fi
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          warnings=$(/usr/lib/llvm-18/bin/clang-tidy -p=./build/compile_commands.json --format-style=.clang-tidy --store-check-profile=. include/settings.h | grep ': warning:' |wc -l)
          if [ $warnings -gt 0 ]
          then
            echo "clang-tidy found warnings!"
            exit 1
          fi

  build-asan-test:
    needs: code-analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: CMake Configure
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DASAN_BUILD=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure

  build-release-test:
    needs: build-asan-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: CMake Configure
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DASAN_BUILD=OFF

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
